### PR TITLE
Updated animal sniffer dependency

### PR DESCRIPTION
**Pull request by MarekB01**
fixes: https://github.com/BroadleafCommerce/QA/issues/4936

As animal sniffer team released an update we upgraded this dependency in our codebase

### CODE REVIEW

**Review by KatrukOV — APPROVED** [review]

**Comment by riteshadhikari17** [comment]
Looks like this plugin was removed by @KatrukOV in [this](https://github.com/BroadleafCommerce/ModuleParent/pull/23/commits/c80e73db4c15ff257f2455ddc17564b3e2273533 ) commit. It's no longer needed.

**Comment by KatrukOV** [comment]
It was a blocker. If it works fine in the new version, we can restore it.

**Comment by riteshadhikari17** [comment]
@KatrukOV I am not sure what was the blocker. I tried this version and I get errors for util package
```
[INFO] --- animal-sniffer-maven-plugin:1.23:check (sniff) @ broadleaf-importer ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java17:1.0
[ERROR] /Users/riteshadhikari/BroadLeafCommerce/github/6.3-ReferenceSite/Importer/src/main/java/com/broadleafcommerce/importer/admin/web/controller/ImporterEndpoint.java:237: Undefined reference: java.util.stream.Stream
[ERROR] /Users/riteshadhikari/BroadLeafCommerce/github/6.3-ReferenceSite/Importer/src/main/java/com/broadleafcommerce/importer/admin/web/controller/ImporterEndpoint.java:237: Undefined reference: java.util.stream.Stream java.util.Set.stream()
```

**Comment by riteshadhikari17** [comment]
Opted to remove the plugin. See QA ticket.

**Pull request closed without merging**
